# Set the name of your application:
APPLICATION = 1-blink

BOARD ?= nrf52840dk
USEMODULE += xtimer

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../../RIOT

include $(RIOTBASE)/Makefile.include