# Set the name of your application:
APPLICATION = 2-basic_shell

BOARD ?= nrf52840dk
USEMODULE += shell
USEMODULE += shell_cmds_default  # This are the default shell commands of RIOT-OS
USEMODULE += xtimer

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../../RIOT

include $(RIOTBASE)/Makefile.include